
-- Create the table for the onboarding conversation flow
CREATE TABLE public.onboarding_steps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  step_name TEXT NOT NULL UNIQUE,
  message TEXT NOT NULL,
  question_key TEXT, -- The key to store the user's answer against (e.g., 'projectType')
  responses JSONB -- Array of possible user responses, e.g., [{ "label": "Portfolio", "next_step_name": "ask_pages" }]
);

-- Add comments to the columns for clarity
COMMENT ON COLUMN public.onboarding_steps.step_name IS 'A unique identifier for the conversation step.';
COMMENT ON COLUMN public.onboarding_steps.message IS 'The message the AI assistant will display at this step.';
COMMENT ON COLUMN public.onboarding_steps.question_key IS 'The key used to store the user''s response in the project details object.';
COMMENT ON COLUMN public.onboarding_steps.responses IS 'A JSON array of response options for the user, including the label for the button and the next step to transition to.';

-- Insert the initial conversation flow data
INSERT INTO public.onboarding_steps (step_name, message, question_key, responses) VALUES
(
  'start',
  'Welcome to NextDaySite! I''m here to help you scope out your new project. What kind of website are you looking for?',
  'projectType',
  '[{"label": "A Business Website", "next_step_name": "ask_pages"}, {"label": "An E-commerce Store", "next_step_name": "ask_pages"}, {"label": "A Portfolio/Blog", "next_step_name": "ask_pages"}, {"label": "Something Else", "next_step_name": "ask_pages"}]'
),
(
  'ask_pages',
  'Sounds great. How many pages do you think you''ll need?',
  'pageCount',
  '[{"label": "1-3 pages", "next_step_name": "ask_branding"}, {"label": "4-6 pages", "next_step_name": "ask_branding"}, {"label": "7+ pages", "next_step_name": "ask_branding"}]'
),
(
  'ask_branding',
  'Got it. Do you need a new logo or a full branding identity package to go with your site?',
  'branding',
  '[{"label": "Yes, I need branding", "next_step_name": "finish"}, {"label": "No, I have a logo", "next_step_name": "finish"}, {"label": "Just a logo refresh", "next_step_name": "finish"}]'
),
(
  'finish',
  'Perfect! I have enough information to create a project brief. To save your progress and view your new project dashboard, let''s get you signed up.',
  'action',
  '[{"label": "Create My Account", "action": "signup"}, {"label": "Login to Existing Account", "action": "login"}]'
);

